spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:2BuCIT7oUWXHYE0o@cluster0.y5xlj.mongodb.net/CVProject?retryWrites=true&w=majority

properties:
  jwt:
    expiration: 14400000
    secret: AJ,~F+bb[p,W2N3L/Q"F&(Q]}TCE=uZ$!/$$x5/Je:(x:^/KL$Whe4X+Jy?bSq,N5UG_"R7[@FDqfNm}#Vp"D'"hm_k)>=R)9NGp}hUL^WZa/*=fWH)%AZ--$t@,H7&*XCq?q2R4S4U]6dUYE2T8%A:$z%6E7L5(&m#fU9@UUNudu=amQ'~;B#MxJN=JdqZ[Ebc*;G:F![?nU)}v'RR@)m;Z:gJ=cVGZwxRva!v'4_?TqbvPCsF#)J-%=#$s$Z,80